spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/babyBack?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    #  在控制台显示数据表
#    show-sql: true
  application:
    name: springcloud-main

  profiles:
    active: pro
  cloud:
    config:
      name: ${spring.application.name}
      profile: ${spring.profiles.active}

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://springcloud-OAuth:4000/oauth/token
      user-authorization-uri: http://springcloud-OAuth:4000/oauth/authorize
    resource:
      token-info-uri: http://springcloud-OAuth:4000/oauth/check_token

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://springcloud-eureka:8761/eureka/



  #redis集群配置
  #spring.cluster.nodes=192.168.1.1:7001,192.168.1.1:7002,192.168.1.1:7003,192.168.1.1:7004,192.168.1.1:7005,192.168.1.1:7006
  #spring.cluster.max-redirects=3

  #哨兵模式
  #sentinel.host1=192.168.1.1
  #sentinel.port1=26379

#sentinel.host2=192.168.1.2
#sentinel.port2=2637

server:
  port: 18080
