spring:
  datasource:
    url: jdbc:mysql://localhost:3306/babyBack?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    #  在控制台显示数据表
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 10000
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 5
        max-concurrency: 20
        concurrency: 10

server:
  port: 18080


mq:
  env: local

message:
  queue:
    name: ${mq.env}.message.queue
  exchange:
    name: ${mq.env}.message.exchange
  routing:
    key:
      name: ${mq.env}.message.routing.key

