spring:
  datasource:
    url: jdbc:mysql://localhost:3306/babyBack?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    #  在控制台显示数据表
    show-sql: true

store-path: "d://jupyter_workplace/2019_summer_practical_training/face_recognition/"