spring:
  mvc:
    servlet:
      load-on-startup: 1
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    sender:
      type: web
logging:
  level:
    root: info
    com.cloud: debug
  file: logs/${spring.application.name}.log
zuul:
  ignored-services: '*'
  sensitiveHeaders:
  routes:
    oauth:
      path: /api-oauth/**
      serviceId: budweiser-oauth
    api-user:
      path: /api-user/**
      serviceId: budweiser-user
    manage:
      path: /api-manage/**
      serviceId: budweiser-manage
    log:
      path: /api-log/**
      serviceId: budweiser-log-center
    file:
      path: /api-file/**
      serviceId: budweiser-file-center
    core:
      path: /api-analyzer/**
      serviceId: budweiser-analyzer
    main:
      path: /api-main/**
      serviceId: budweiser-main
  host:
    connect-timeout-millis: 4000
    socket-timeout-millis: 6000
  add-proxy-headers: true
  ribbon:
    eager-load:
      enabled: true
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 3
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
cron:
  black-ip: 0 0/5 * * * ?