logging:
  level:
    root: info
    com.cloud: debug
  file: logs/${spring.application.name}.log
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://47.105.220.129:1433;DatabaseName=BW-EMS
    username: sa
    password: G1veMeP@ss
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1
  rabbitmq:
    host: localhost
    port: 5672
    username: bacco
    password: bacco-dev
    virtual-host: /
  redis:
    host: localhost
    port: 6379
    password:
    database: 1
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  mvc:
    servlet:
      load-on-startup: 1
  aop:
    proxy-target-class: true
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    sender:
      type: web
  activiti:
    database-schema-update: true
mybatis:
  type-aliases-package: com.anxuan.model.core
  mapper-locations: classpath:/mybatis-mappers/*
  configuration:
    mapUnderscoreToCamelCase: true
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8080/api-oauth/user-me
      prefer-token-info: false
