spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://hahahoho.mysql.database.chinacloudapi.cn:3306/baby_back?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: ENC(f5BNh1AUMlCACAZVZUmHT4WnyuFALwx8XzZqR5MG03g=)
    password: ENC(vEJKeKNvw2YZvXSmCo+JR6HNJ7kLg6Mc)

jasypt:
  encryptor:
    password: hahahohohehe