zuul:
  routes:
    springcloud-OAuth:
      path: /api/auth/**
      serviceId: springcloud-OAuth
    springcloud-admin:
      path: /api/admin/**
      serviceId: springcloud-admin-biz
    springcloud-main:
      path: /api/main/**
      serviceId: springcloud-main
        #    sct-monitor:
        #      path: /api/monitor/**
        #      serviceId: sct-monitor
        #    sct-zipkin:
        #      path: /api/zipkin/**
        #      serviceId: sct-zipkin
        #    sct-eureka:
      #      path: /api/eureka/**
      #      serviceId: sct-eureka

